################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../Example/User/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../Example/User/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../Example/User/Source/FilteringFunctions/arm_conv_f32.c \
../Example/User/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../Example/User/Source/FilteringFunctions/arm_conv_fast_q15.c \
../Example/User/Source/FilteringFunctions/arm_conv_fast_q31.c \
../Example/User/Source/FilteringFunctions/arm_conv_opt_q15.c \
../Example/User/Source/FilteringFunctions/arm_conv_opt_q7.c \
../Example/User/Source/FilteringFunctions/arm_conv_partial_f32.c \
../Example/User/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../Example/User/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../Example/User/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../Example/User/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../Example/User/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../Example/User/Source/FilteringFunctions/arm_conv_partial_q15.c \
../Example/User/Source/FilteringFunctions/arm_conv_partial_q31.c \
../Example/User/Source/FilteringFunctions/arm_conv_partial_q7.c \
../Example/User/Source/FilteringFunctions/arm_conv_q15.c \
../Example/User/Source/FilteringFunctions/arm_conv_q31.c \
../Example/User/Source/FilteringFunctions/arm_conv_q7.c \
../Example/User/Source/FilteringFunctions/arm_correlate_f32.c \
../Example/User/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../Example/User/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../Example/User/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../Example/User/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../Example/User/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../Example/User/Source/FilteringFunctions/arm_correlate_q15.c \
../Example/User/Source/FilteringFunctions/arm_correlate_q31.c \
../Example/User/Source/FilteringFunctions/arm_correlate_q7.c \
../Example/User/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../Example/User/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../Example/User/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../Example/User/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../Example/User/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../Example/User/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../Example/User/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../Example/User/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../Example/User/Source/FilteringFunctions/arm_fir_f32.c \
../Example/User/Source/FilteringFunctions/arm_fir_fast_q15.c \
../Example/User/Source/FilteringFunctions/arm_fir_fast_q31.c \
../Example/User/Source/FilteringFunctions/arm_fir_init_f32.c \
../Example/User/Source/FilteringFunctions/arm_fir_init_q15.c \
../Example/User/Source/FilteringFunctions/arm_fir_init_q31.c \
../Example/User/Source/FilteringFunctions/arm_fir_init_q7.c \
../Example/User/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../Example/User/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../Example/User/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../Example/User/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../Example/User/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../Example/User/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../Example/User/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../Example/User/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../Example/User/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../Example/User/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../Example/User/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../Example/User/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../Example/User/Source/FilteringFunctions/arm_fir_q15.c \
../Example/User/Source/FilteringFunctions/arm_fir_q31.c \
../Example/User/Source/FilteringFunctions/arm_fir_q7.c \
../Example/User/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../Example/User/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../Example/User/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../Example/User/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../Example/User/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../Example/User/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../Example/User/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../Example/User/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../Example/User/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../Example/User/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../Example/User/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../Example/User/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../Example/User/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../Example/User/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../Example/User/Source/FilteringFunctions/arm_lms_f32.c \
../Example/User/Source/FilteringFunctions/arm_lms_init_f32.c \
../Example/User/Source/FilteringFunctions/arm_lms_init_q15.c \
../Example/User/Source/FilteringFunctions/arm_lms_init_q31.c \
../Example/User/Source/FilteringFunctions/arm_lms_norm_f32.c \
../Example/User/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../Example/User/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../Example/User/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../Example/User/Source/FilteringFunctions/arm_lms_norm_q15.c \
../Example/User/Source/FilteringFunctions/arm_lms_norm_q31.c \
../Example/User/Source/FilteringFunctions/arm_lms_q15.c \
../Example/User/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./Example/User/Source/FilteringFunctions/arm_conv_f32.o \
./Example/User/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./Example/User/Source/FilteringFunctions/arm_conv_fast_q15.o \
./Example/User/Source/FilteringFunctions/arm_conv_fast_q31.o \
./Example/User/Source/FilteringFunctions/arm_conv_opt_q15.o \
./Example/User/Source/FilteringFunctions/arm_conv_opt_q7.o \
./Example/User/Source/FilteringFunctions/arm_conv_partial_f32.o \
./Example/User/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./Example/User/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./Example/User/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./Example/User/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./Example/User/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./Example/User/Source/FilteringFunctions/arm_conv_partial_q15.o \
./Example/User/Source/FilteringFunctions/arm_conv_partial_q31.o \
./Example/User/Source/FilteringFunctions/arm_conv_partial_q7.o \
./Example/User/Source/FilteringFunctions/arm_conv_q15.o \
./Example/User/Source/FilteringFunctions/arm_conv_q31.o \
./Example/User/Source/FilteringFunctions/arm_conv_q7.o \
./Example/User/Source/FilteringFunctions/arm_correlate_f32.o \
./Example/User/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./Example/User/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./Example/User/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./Example/User/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./Example/User/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./Example/User/Source/FilteringFunctions/arm_correlate_q15.o \
./Example/User/Source/FilteringFunctions/arm_correlate_q31.o \
./Example/User/Source/FilteringFunctions/arm_correlate_q7.o \
./Example/User/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./Example/User/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./Example/User/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./Example/User/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./Example/User/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./Example/User/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./Example/User/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./Example/User/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./Example/User/Source/FilteringFunctions/arm_fir_f32.o \
./Example/User/Source/FilteringFunctions/arm_fir_fast_q15.o \
./Example/User/Source/FilteringFunctions/arm_fir_fast_q31.o \
./Example/User/Source/FilteringFunctions/arm_fir_init_f32.o \
./Example/User/Source/FilteringFunctions/arm_fir_init_q15.o \
./Example/User/Source/FilteringFunctions/arm_fir_init_q31.o \
./Example/User/Source/FilteringFunctions/arm_fir_init_q7.o \
./Example/User/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./Example/User/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./Example/User/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./Example/User/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./Example/User/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./Example/User/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./Example/User/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./Example/User/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./Example/User/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./Example/User/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./Example/User/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./Example/User/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./Example/User/Source/FilteringFunctions/arm_fir_q15.o \
./Example/User/Source/FilteringFunctions/arm_fir_q31.o \
./Example/User/Source/FilteringFunctions/arm_fir_q7.o \
./Example/User/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./Example/User/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./Example/User/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./Example/User/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./Example/User/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./Example/User/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./Example/User/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./Example/User/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./Example/User/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./Example/User/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./Example/User/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./Example/User/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./Example/User/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./Example/User/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./Example/User/Source/FilteringFunctions/arm_lms_f32.o \
./Example/User/Source/FilteringFunctions/arm_lms_init_f32.o \
./Example/User/Source/FilteringFunctions/arm_lms_init_q15.o \
./Example/User/Source/FilteringFunctions/arm_lms_init_q31.o \
./Example/User/Source/FilteringFunctions/arm_lms_norm_f32.o \
./Example/User/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./Example/User/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./Example/User/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./Example/User/Source/FilteringFunctions/arm_lms_norm_q15.o \
./Example/User/Source/FilteringFunctions/arm_lms_norm_q31.o \
./Example/User/Source/FilteringFunctions/arm_lms_q15.o \
./Example/User/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./Example/User/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./Example/User/Source/FilteringFunctions/arm_conv_f32.d \
./Example/User/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./Example/User/Source/FilteringFunctions/arm_conv_fast_q15.d \
./Example/User/Source/FilteringFunctions/arm_conv_fast_q31.d \
./Example/User/Source/FilteringFunctions/arm_conv_opt_q15.d \
./Example/User/Source/FilteringFunctions/arm_conv_opt_q7.d \
./Example/User/Source/FilteringFunctions/arm_conv_partial_f32.d \
./Example/User/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./Example/User/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./Example/User/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./Example/User/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./Example/User/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./Example/User/Source/FilteringFunctions/arm_conv_partial_q15.d \
./Example/User/Source/FilteringFunctions/arm_conv_partial_q31.d \
./Example/User/Source/FilteringFunctions/arm_conv_partial_q7.d \
./Example/User/Source/FilteringFunctions/arm_conv_q15.d \
./Example/User/Source/FilteringFunctions/arm_conv_q31.d \
./Example/User/Source/FilteringFunctions/arm_conv_q7.d \
./Example/User/Source/FilteringFunctions/arm_correlate_f32.d \
./Example/User/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./Example/User/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./Example/User/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./Example/User/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./Example/User/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./Example/User/Source/FilteringFunctions/arm_correlate_q15.d \
./Example/User/Source/FilteringFunctions/arm_correlate_q31.d \
./Example/User/Source/FilteringFunctions/arm_correlate_q7.d \
./Example/User/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./Example/User/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./Example/User/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./Example/User/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./Example/User/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./Example/User/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./Example/User/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./Example/User/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./Example/User/Source/FilteringFunctions/arm_fir_f32.d \
./Example/User/Source/FilteringFunctions/arm_fir_fast_q15.d \
./Example/User/Source/FilteringFunctions/arm_fir_fast_q31.d \
./Example/User/Source/FilteringFunctions/arm_fir_init_f32.d \
./Example/User/Source/FilteringFunctions/arm_fir_init_q15.d \
./Example/User/Source/FilteringFunctions/arm_fir_init_q31.d \
./Example/User/Source/FilteringFunctions/arm_fir_init_q7.d \
./Example/User/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./Example/User/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./Example/User/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./Example/User/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./Example/User/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./Example/User/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./Example/User/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./Example/User/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./Example/User/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./Example/User/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./Example/User/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./Example/User/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./Example/User/Source/FilteringFunctions/arm_fir_q15.d \
./Example/User/Source/FilteringFunctions/arm_fir_q31.d \
./Example/User/Source/FilteringFunctions/arm_fir_q7.d \
./Example/User/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./Example/User/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./Example/User/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./Example/User/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./Example/User/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./Example/User/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./Example/User/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./Example/User/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./Example/User/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./Example/User/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./Example/User/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./Example/User/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./Example/User/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./Example/User/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./Example/User/Source/FilteringFunctions/arm_lms_f32.d \
./Example/User/Source/FilteringFunctions/arm_lms_init_f32.d \
./Example/User/Source/FilteringFunctions/arm_lms_init_q15.d \
./Example/User/Source/FilteringFunctions/arm_lms_init_q31.d \
./Example/User/Source/FilteringFunctions/arm_lms_norm_f32.d \
./Example/User/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./Example/User/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./Example/User/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./Example/User/Source/FilteringFunctions/arm_lms_norm_q15.d \
./Example/User/Source/FilteringFunctions/arm_lms_norm_q31.d \
./Example/User/Source/FilteringFunctions/arm_lms_q15.d \
./Example/User/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
Example/User/Source/FilteringFunctions/%.o: ../Example/User/Source/FilteringFunctions/%.c Example/User/Source/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -D__FPU_PRESENT=1 -DSTM32F746xx -DUSE_HAL_DRIVER -DUSE_STM32746G_DISCO -DUSE_IOEXPANDER -DARM_MATH_CM7 -c -I../../../Inc -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../../../../../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../../../../../../Drivers/BSP/STM32746G-Discovery -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Utilities/Log -I../../../../../../../Utilities/Fonts -I../../../../../../../Utilities/CPU -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Example-2f-User-2f-Source-2f-FilteringFunctions

clean-Example-2f-User-2f-Source-2f-FilteringFunctions:
	-$(RM) ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d ./Example/User/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o ./Example/User/Source/FilteringFunctions/arm_conv_f32.d ./Example/User/Source/FilteringFunctions/arm_conv_f32.o ./Example/User/Source/FilteringFunctions/arm_conv_fast_opt_q15.d ./Example/User/Source/FilteringFunctions/arm_conv_fast_opt_q15.o ./Example/User/Source/FilteringFunctions/arm_conv_fast_q15.d ./Example/User/Source/FilteringFunctions/arm_conv_fast_q15.o ./Example/User/Source/FilteringFunctions/arm_conv_fast_q31.d ./Example/User/Source/FilteringFunctions/arm_conv_fast_q31.o ./Example/User/Source/FilteringFunctions/arm_conv_opt_q15.d ./Example/User/Source/FilteringFunctions/arm_conv_opt_q15.o ./Example/User/Source/FilteringFunctions/arm_conv_opt_q7.d ./Example/User/Source/FilteringFunctions/arm_conv_opt_q7.o ./Example/User/Source/FilteringFunctions/arm_conv_partial_f32.d ./Example/User/Source/FilteringFunctions/arm_conv_partial_f32.o ./Example/User/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d ./Example/User/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o ./Example/User/Source/FilteringFunctions/arm_conv_partial_fast_q15.d ./Example/User/Source/FilteringFunctions/arm_conv_partial_fast_q15.o ./Example/User/Source/FilteringFunctions/arm_conv_partial_fast_q31.d ./Example/User/Source/FilteringFunctions/arm_conv_partial_fast_q31.o ./Example/User/Source/FilteringFunctions/arm_conv_partial_opt_q15.d ./Example/User/Source/FilteringFunctions/arm_conv_partial_opt_q15.o ./Example/User/Source/FilteringFunctions/arm_conv_partial_opt_q7.d ./Example/User/Source/FilteringFunctions/arm_conv_partial_opt_q7.o ./Example/User/Source/FilteringFunctions/arm_conv_partial_q15.d ./Example/User/Source/FilteringFunctions/arm_conv_partial_q15.o ./Example/User/Source/FilteringFunctions/arm_conv_partial_q31.d ./Example/User/Source/FilteringFunctions/arm_conv_partial_q31.o ./Example/User/Source/FilteringFunctions/arm_conv_partial_q7.d ./Example/User/Source/FilteringFunctions/arm_conv_partial_q7.o ./Example/User/Source/FilteringFunctions/arm_conv_q15.d ./Example/User/Source/FilteringFunctions/arm_conv_q15.o ./Example/User/Source/FilteringFunctions/arm_conv_q31.d ./Example/User/Source/FilteringFunctions/arm_conv_q31.o ./Example/User/Source/FilteringFunctions/arm_conv_q7.d ./Example/User/Source/FilteringFunctions/arm_conv_q7.o ./Example/User/Source/FilteringFunctions/arm_correlate_f32.d ./Example/User/Source/FilteringFunctions/arm_correlate_f32.o ./Example/User/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d ./Example/User/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o ./Example/User/Source/FilteringFunctions/arm_correlate_fast_q15.d ./Example/User/Source/FilteringFunctions/arm_correlate_fast_q15.o ./Example/User/Source/FilteringFunctions/arm_correlate_fast_q31.d ./Example/User/Source/FilteringFunctions/arm_correlate_fast_q31.o ./Example/User/Source/FilteringFunctions/arm_correlate_opt_q15.d ./Example/User/Source/FilteringFunctions/arm_correlate_opt_q15.o ./Example/User/Source/FilteringFunctions/arm_correlate_opt_q7.d ./Example/User/Source/FilteringFunctions/arm_correlate_opt_q7.o ./Example/User/Source/FilteringFunctions/arm_correlate_q15.d ./Example/User/Source/FilteringFunctions/arm_correlate_q15.o ./Example/User/Source/FilteringFunctions/arm_correlate_q31.d ./Example/User/Source/FilteringFunctions/arm_correlate_q31.o ./Example/User/Source/FilteringFunctions/arm_correlate_q7.d ./Example/User/Source/FilteringFunctions/arm_correlate_q7.o ./Example/User/Source/FilteringFunctions/arm_fir_decimate_f32.d ./Example/User/Source/FilteringFunctions/arm_fir_decimate_f32.o
	-$(RM) ./Example/User/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d ./Example/User/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o ./Example/User/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d ./Example/User/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o ./Example/User/Source/FilteringFunctions/arm_fir_decimate_init_f32.d ./Example/User/Source/FilteringFunctions/arm_fir_decimate_init_f32.o ./Example/User/Source/FilteringFunctions/arm_fir_decimate_init_q15.d ./Example/User/Source/FilteringFunctions/arm_fir_decimate_init_q15.o ./Example/User/Source/FilteringFunctions/arm_fir_decimate_init_q31.d ./Example/User/Source/FilteringFunctions/arm_fir_decimate_init_q31.o ./Example/User/Source/FilteringFunctions/arm_fir_decimate_q15.d ./Example/User/Source/FilteringFunctions/arm_fir_decimate_q15.o ./Example/User/Source/FilteringFunctions/arm_fir_decimate_q31.d ./Example/User/Source/FilteringFunctions/arm_fir_decimate_q31.o ./Example/User/Source/FilteringFunctions/arm_fir_f32.d ./Example/User/Source/FilteringFunctions/arm_fir_f32.o ./Example/User/Source/FilteringFunctions/arm_fir_fast_q15.d ./Example/User/Source/FilteringFunctions/arm_fir_fast_q15.o ./Example/User/Source/FilteringFunctions/arm_fir_fast_q31.d ./Example/User/Source/FilteringFunctions/arm_fir_fast_q31.o ./Example/User/Source/FilteringFunctions/arm_fir_init_f32.d ./Example/User/Source/FilteringFunctions/arm_fir_init_f32.o ./Example/User/Source/FilteringFunctions/arm_fir_init_q15.d ./Example/User/Source/FilteringFunctions/arm_fir_init_q15.o ./Example/User/Source/FilteringFunctions/arm_fir_init_q31.d ./Example/User/Source/FilteringFunctions/arm_fir_init_q31.o ./Example/User/Source/FilteringFunctions/arm_fir_init_q7.d ./Example/User/Source/FilteringFunctions/arm_fir_init_q7.o ./Example/User/Source/FilteringFunctions/arm_fir_interpolate_f32.d ./Example/User/Source/FilteringFunctions/arm_fir_interpolate_f32.o ./Example/User/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d ./Example/User/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o ./Example/User/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d ./Example/User/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o ./Example/User/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d ./Example/User/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o ./Example/User/Source/FilteringFunctions/arm_fir_interpolate_q15.d ./Example/User/Source/FilteringFunctions/arm_fir_interpolate_q15.o ./Example/User/Source/FilteringFunctions/arm_fir_interpolate_q31.d ./Example/User/Source/FilteringFunctions/arm_fir_interpolate_q31.o ./Example/User/Source/FilteringFunctions/arm_fir_lattice_f32.d ./Example/User/Source/FilteringFunctions/arm_fir_lattice_f32.o ./Example/User/Source/FilteringFunctions/arm_fir_lattice_init_f32.d ./Example/User/Source/FilteringFunctions/arm_fir_lattice_init_f32.o ./Example/User/Source/FilteringFunctions/arm_fir_lattice_init_q15.d ./Example/User/Source/FilteringFunctions/arm_fir_lattice_init_q15.o ./Example/User/Source/FilteringFunctions/arm_fir_lattice_init_q31.d ./Example/User/Source/FilteringFunctions/arm_fir_lattice_init_q31.o ./Example/User/Source/FilteringFunctions/arm_fir_lattice_q15.d ./Example/User/Source/FilteringFunctions/arm_fir_lattice_q15.o ./Example/User/Source/FilteringFunctions/arm_fir_lattice_q31.d ./Example/User/Source/FilteringFunctions/arm_fir_lattice_q31.o ./Example/User/Source/FilteringFunctions/arm_fir_q15.d ./Example/User/Source/FilteringFunctions/arm_fir_q15.o ./Example/User/Source/FilteringFunctions/arm_fir_q31.d ./Example/User/Source/FilteringFunctions/arm_fir_q31.o ./Example/User/Source/FilteringFunctions/arm_fir_q7.d ./Example/User/Source/FilteringFunctions/arm_fir_q7.o ./Example/User/Source/FilteringFunctions/arm_fir_sparse_f32.d ./Example/User/Source/FilteringFunctions/arm_fir_sparse_f32.o ./Example/User/Source/FilteringFunctions/arm_fir_sparse_init_f32.d ./Example/User/Source/FilteringFunctions/arm_fir_sparse_init_f32.o ./Example/User/Source/FilteringFunctions/arm_fir_sparse_init_q15.d ./Example/User/Source/FilteringFunctions/arm_fir_sparse_init_q15.o ./Example/User/Source/FilteringFunctions/arm_fir_sparse_init_q31.d ./Example/User/Source/FilteringFunctions/arm_fir_sparse_init_q31.o ./Example/User/Source/FilteringFunctions/arm_fir_sparse_init_q7.d ./Example/User/Source/FilteringFunctions/arm_fir_sparse_init_q7.o ./Example/User/Source/FilteringFunctions/arm_fir_sparse_q15.d ./Example/User/Source/FilteringFunctions/arm_fir_sparse_q15.o ./Example/User/Source/FilteringFunctions/arm_fir_sparse_q31.d ./Example/User/Source/FilteringFunctions/arm_fir_sparse_q31.o ./Example/User/Source/FilteringFunctions/arm_fir_sparse_q7.d ./Example/User/Source/FilteringFunctions/arm_fir_sparse_q7.o ./Example/User/Source/FilteringFunctions/arm_iir_lattice_f32.d ./Example/User/Source/FilteringFunctions/arm_iir_lattice_f32.o ./Example/User/Source/FilteringFunctions/arm_iir_lattice_init_f32.d ./Example/User/Source/FilteringFunctions/arm_iir_lattice_init_f32.o ./Example/User/Source/FilteringFunctions/arm_iir_lattice_init_q15.d ./Example/User/Source/FilteringFunctions/arm_iir_lattice_init_q15.o ./Example/User/Source/FilteringFunctions/arm_iir_lattice_init_q31.d ./Example/User/Source/FilteringFunctions/arm_iir_lattice_init_q31.o ./Example/User/Source/FilteringFunctions/arm_iir_lattice_q15.d ./Example/User/Source/FilteringFunctions/arm_iir_lattice_q15.o ./Example/User/Source/FilteringFunctions/arm_iir_lattice_q31.d ./Example/User/Source/FilteringFunctions/arm_iir_lattice_q31.o ./Example/User/Source/FilteringFunctions/arm_lms_f32.d ./Example/User/Source/FilteringFunctions/arm_lms_f32.o ./Example/User/Source/FilteringFunctions/arm_lms_init_f32.d ./Example/User/Source/FilteringFunctions/arm_lms_init_f32.o ./Example/User/Source/FilteringFunctions/arm_lms_init_q15.d ./Example/User/Source/FilteringFunctions/arm_lms_init_q15.o ./Example/User/Source/FilteringFunctions/arm_lms_init_q31.d
	-$(RM) ./Example/User/Source/FilteringFunctions/arm_lms_init_q31.o ./Example/User/Source/FilteringFunctions/arm_lms_norm_f32.d ./Example/User/Source/FilteringFunctions/arm_lms_norm_f32.o ./Example/User/Source/FilteringFunctions/arm_lms_norm_init_f32.d ./Example/User/Source/FilteringFunctions/arm_lms_norm_init_f32.o ./Example/User/Source/FilteringFunctions/arm_lms_norm_init_q15.d ./Example/User/Source/FilteringFunctions/arm_lms_norm_init_q15.o ./Example/User/Source/FilteringFunctions/arm_lms_norm_init_q31.d ./Example/User/Source/FilteringFunctions/arm_lms_norm_init_q31.o ./Example/User/Source/FilteringFunctions/arm_lms_norm_q15.d ./Example/User/Source/FilteringFunctions/arm_lms_norm_q15.o ./Example/User/Source/FilteringFunctions/arm_lms_norm_q31.d ./Example/User/Source/FilteringFunctions/arm_lms_norm_q31.o ./Example/User/Source/FilteringFunctions/arm_lms_q15.d ./Example/User/Source/FilteringFunctions/arm_lms_q15.o ./Example/User/Source/FilteringFunctions/arm_lms_q31.d ./Example/User/Source/FilteringFunctions/arm_lms_q31.o

.PHONY: clean-Example-2f-User-2f-Source-2f-FilteringFunctions

